### ISSUE TITLE
Merge changelog action is failing

### ISSUE THREAD

**Issue by BenFradet** [47degrees/.github#10]
https://github.com/47degrees/pbdirect/runs/542013766#step:8:10

**Comment by BenFradet** [comment]
affected repos seem to be:

- pbdirect
- sbt-org-policies
- fetch
- petstore4s

others seem to be fine

**Comment by juanpedromoreno** [comment]
It happens for repositories where the `merge` mode is disabled. Fix: https://github.com/47degrees/.github/pull/11
